### ISSUE TITLE
Make it work on mobile

### ISSUE THREAD

**Issue by Kevinpgalligan** [Kevinpgalligan/slingshot-chess#5]
Doesn't work in a mobile browser at the moment. At all. Pieces are blurry and you can't fire them.

**Comment by badcock4412** [comment]
https://github.com/badcock4412/slingshot-chess/tree/dev-mobile

took a swing at it.  Got it working on my iPhone (latest OS / current hardware) but still some work to do somewhere for Android, so no PR yet.

for the blurriness had to scale some render params and the cursor position -> coords with the window.devicePixelRatio:
https://github.com/badcock4412/slingshot-chess/blob/b1a5d8157616f4682211ed238e5cb99169241427/slingshotchess.js#L444

also had to do some work to prevent drag from scrolling, but overall pretty happy with how it's running on iOS now.

if you have Golang APK (golang.org) you can go run webserver.go from my repo to spin up a webserver for testing over wifi with real devices :)

**Comment by Kevinpgalligan** [comment]
Very cool! A friend of mine had a crack at fixing this, but I don't know if he solved the drag issue. I'll merge this when you're finished & when I get the chance, do you want me to give you credit in the repo / on the website?

**Comment by badcock4412** [comment]
if I get it working I'll let you know!  A special thanks on the repo would be plenty - if I get it going of course!

**Comment by Kevinpgalligan** [comment]
Seems to be working now.

**Comment by Kevinpgalligan** [comment]
Although, the firing circles are quite small to find with your finger.
